services:
  # MongoDB database for sharing service
  mongodb:
    image: mongo:6.0
    container_name: watchthis-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: media-service
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d
    tmpfs:
      - /data/db # Use tmpfs for ephemeral data storage
    networks:
      - watchthis-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # PostgreSQL database for user and media services
  postgresql:
    image: postgres:16
    container_name: watchthis-postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: watchthis
      POSTGRES_USER: watchthis
      POSTGRES_PASSWORD: watchthis_dev
    ports:
      - "5433:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d
    tmpfs:
      - /var/lib/postgresql/data # Use tmpfs for ephemeral data storage
    networks:
      - watchthis-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U watchthis -d watchthis"]
      interval: 10s
      timeout: 5s
      retries: 5

  # WatchThis Home Service
  watchthis-home-service:
    image: ghcr.io/aimeerivers/watchthis-home-service:latest
    container_name: watchthis-home-service
    restart: unless-stopped
    ports:
      - "7279:7279"
    environment:
      # Server Configuration
      PORT: 7279
      BASE_URL: http://localhost:7279
      NODE_ENV: development

      # Service URLs - using container names for internal communication
      USER_SERVICE_URL: http://watchthis-user-service:8583
      USER_SERVICE_PUBLIC_URL: http://localhost:8583
    networks:
      - watchthis-network
    depends_on:
      watchthis-user-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7279/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # WatchThis Media Service
  watchthis-media-service:
    image: ghcr.io/aimeerivers/watchthis-media-service:latest
    container_name: watchthis-media-service
    restart: unless-stopped
    ports:
      - "7769:7769"
    environment:
      # Server Configuration
      PORT: 7769
      BASE_URL: http://localhost:7769
      NODE_ENV: development

      # Database Configuration - using container name (internal port still 5432)
      DATABASE_URL: postgresql://watchthis:watchthis_dev@postgresql:5432/watchthis_media

      # Service URLs - using container names for internal communication
      USER_SERVICE_URL: http://watchthis-user-service:8583
    command: ["sh", "-c", "npm run database:setup && npm start"]
    networks:
      - watchthis-network
    depends_on:
      postgresql:
        condition: service_healthy
      watchthis-user-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7769/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # WatchThis Sharing Service
  watchthis-sharing-service:
    image: ghcr.io/aimeerivers/watchthis-sharing-service:latest
    container_name: watchthis-sharing-service
    restart: unless-stopped
    ports:
      - "8372:8372"
    environment:
      # Server Configuration
      PORT: 8372
      BASE_URL: http://localhost:8372
      NODE_ENV: development

      # Database Configuration - using container name (internal port still 27017)
      MONGO_URL: mongodb://mongodb:27017/sharing-service

      # Service URLs - using container names for internal communication
      HOME_SERVICE_URL: http://watchthis-home-service:7279
      MEDIA_SERVICE_URL: http://watchthis-media-service:7769
      USER_SERVICE_URL: http://watchthis-user-service:8583
    networks:
      - watchthis-network
    depends_on:
      mongodb:
        condition: service_healthy
      watchthis-home-service:
        condition: service_healthy
      watchthis-media-service:
        condition: service_healthy
      watchthis-user-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8372/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # WatchThis User Service
  watchthis-user-service:
    image: ghcr.io/aimeerivers/watchthis-user-service:latest
    container_name: watchthis-user-service
    restart: unless-stopped
    ports:
      - "8583:8583"
    environment:
      # Server Configuration
      BASE_URL: http://localhost:8583
      PORT: 8583
      NODE_ENV: development

      # Database Configuration - using container name (internal port still 5432)
      DATABASE_URL: postgresql://watchthis:watchthis_dev@postgresql:5432/watchthis_user

      # Session Configuration
      SESSION_SECRET: test-session-secret-for-e2e-testing

      # JWT Configuration
      JWT_SECRET: test-jwt-secret-key-for-e2e-testing-make-it-long-and-secure
      JWT_EXPIRES_IN: 24h
      JWT_REFRESH_EXPIRES_IN: 7d
    command: ["sh", "-c", "npm run database:setup && npm start"]
    networks:
      - watchthis-network
    depends_on:
      postgresql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8583/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  watchthis-network:
    driver: bridge
    name: watchthis-network
