name: Run Cucumber features

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: node

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Chromium browser
        run: npm run playwright:install:chromium

      - name: Run Cucumber features
        run: npm run cucumber

      - name: Upload Cucumber report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: reports/
          retention-days: 5
